# resources:
    # This is how we would reference a template from a different repository
  # repositories:
  #   - repository: templates
  #     type: git
  #     name: azure-pipelines-templates
  #     ref: refs/tags/v1.0.0

trigger:
  branches:
    include:
      - main
      - master
      - develop
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - TODO.md
      - LICENSE
      - .gitignore
      - .gitattributes
      - .vscode
      - .github
      - .azure-pipelines
      - .git
      - ./docs

steps:
  - template: /.azure-pipelines/set-version-date.yml
  - template: /.azure-pipelines/build-dotnetcore.yml
    parameters:
      slnFile: 'FluentRegex.sln'
      buildConfiguration: 'Release'
      sdkVersion: '8.x'
      publishWebProjects: false
      tests:
        - src/FluentRegex.Tests/FluentRegex.Tests.csproj

